language: java
sudo: false
notifications:
  hipchat:
    rooms:
      secure: mkv78H5QfIS/4czuSXLaBx4DNnslVlpBatj0WMKBRGqnnIS6QjVucJRsJ2XTI2FfUMAm/1sjVDSe1ebwArd8S5IeY/wbQH+nk1PK+CckjmFl3nle6sGjRcDGmQCyqZKBS4GgI4SRN8aPBJNTDtnrJVeRAD4SHO+U16WJozbHOm7fpTSLhr/pJDsWqpEEDqdsrxMSnstrAcvnk2Ietr2v0I4pOuTvZy/zdH1F7yHhnmI/5A5IzTviDoWxPsK5uqqNZgmm8GC+Iq45FZNx9a1xPkcEqhmoBmMCrp+6mrKRawOJ21V6LYjjkl+9hJsSIta1a2WuOSXmovwwkpU6RFczFbQxLsQdYIKdpQ+0BYLZcGxEeXSHWzdRt3MycJbRCYt3lssQtSyeN/Ra3ORzR+kwdElSaWxm1gohVVm4GEEKKz8z4/UE7QLJ15tQ1s8jQl2ZEqL8XWuL4ukYvTuphNmcudE6DFFeuobD/yLZCLq5lKdJBCMLW3D0+21uFTCeEOzRquOfMIMWeceMaEemWa9HFAWUXVwt6vkYxjhj8SmU4KSL9lBwlt2Mk5AyO3ZThOcyV4QIK+CShahBrtixL443VUgWu25im2fCRZnobStATd0cTyXJWUwHAV/kr8NLf2RprAMvkprhNJay2wzEFVpyQZwXdqn3VEhl1d2iKMgtb6g=
