language: java
sudo: false
notifications:
  slack:
    secure: f0Yu30Ccmj2F0DXoihj7bRmY61X7QtGCeqQtXvP9VFwW6KxfuAEKCGgZGEZVmIVcUX5p473mN091+CGUfB19P5/CWOrhbP5tfQReSIKYQn/jH3NVaSyik+3wO7AsFEYM+S+Yba/W7fWZ66A1srzf4+X9ud0OiR6JCfVUZ28liFWpgVAFcvQCWP3Dh7Nm6vneb9n18ts+7AR+i/JL7d/acQ/971b12c6hhne2hkpa6hiwxb3tS2Dqs4yc952+RutNhY3cpQkF6KfHZBuK319hJSdFME2Or8Hn4FADNRvwANoVWKX4QP/cXFN0q9Kp4CrIh+COu607R15Qq7lrMcl2ojaMqqYYUAABtMEKNpL2JvX5KaE9Mv0NyU6aAK8r7ER0rSDDls0IGPyaVMPlfJM5QaW4wtTCWbjSZKIF4hQa8OGDw741YopCbZqy2Psv4QFcGXjnDIlWa2Jny+4g3uwai3uHAIbXk10j/Vr95rU3+ntkNprgi+vGF+hC3v3VfCo15Y1P8v6wELOghT8IkV9O/H+ZX3TsMdn6ZhT4FQZzxeL8b0MCJFSCCXuR3KJFrfpx/xFj2ju/yyMz0HG+XcvgrUQBzdBCkFpvt9aTqBqHVWCSWDFmMk+HvdYWqbrGJGCtLI7aYcNEJ46Ap1b2n/JPsNACzV/IKTva2UnecgOSdeA=
deploy:
  provider: releases
  api_key:
    secure: bdp/O4FbKObVJLA0p1UsvToqzPE7fOqz5PswbEx+JTL7r3LJ8B2uWSmWUHXpPCXo2cEYUT0MXASaXe75iDXtHdXfivYGfcH7PTmhQO5VVS9Az7pV3C8f/rKsmyBzN17/gh/sJFwBcWDDOD2VbDP1hs5YClPctVJd8RRFgROYoM/3VO85k/FpoiReYiKg1eSigdWl8AwLBaALQcgiP0JxXomtCDxLTNYAK+dCzr1FFha+a5DOgpG6e/J1PhUfvL5FhY3OEfmdO0EqBpxo/doinlwTx2TDUr3Xi4I+T7wKa1xBQVJ7weJZM/fnS11pPKhIginVoxrxb49mjEHXYKk7ywuLyMQ1V/fj56AMNiRnx+uq7GpWkUHfUOs8bPm35cJTWNYHcM5wgbCCQn6mrEOmRMY08d+nIp800hebaI8Nrw+2L18yXp+CXvy9pfVGS+KIkKDYmWW7Ht/jCZS6Hl3XbiPA4LpxvIEIa78N3raNk6EC3u9ept8ANV9n4qpEN/zzb0g8cGSy4STq4AR7CfCohLcV+J8tSNL8U2XBOHEHvJvz6Ta4cSP7ZVoxomVlmNzRgojuSsFt3zsqX/5hObuRLEEEEQ9KzfL9tQs+gC97sXkpUo+zmKblnuLpz2hz6ard/yAuh1U0qMUy2GA6junGMsrURa8iv4msOcW+WENm5GM=
  file: build/distributions/xld-rpm-plugin-5.0.2.xldp
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-rpm-plugin
